# Generated by Django 4.2 on 2024-10-04 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profileimage_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='background_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
