# Generated by Django 4.2 on 2024-10-11 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_backgroundimage_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='background_image',
            field=models.ImageField(default='defaults.jpg', upload_to='profile_image', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
