# Generated by Django 4.2 on 2024-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
