# Generated by Django 4.2 on 2024-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('None', 'None'), ('Male', 'Male')], max_length=10, null=True),
        ),
    ]
