# Generated by Django 4.2 on 2024-10-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_remove_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('None', 'None')], max_length=10, null=True),
        ),
    ]
